// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggaiumycedvxpeylmfxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnYWl1bXljZWR2eHBleWxtZnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjYyMjMsImV4cCI6MjA2Mzc0MjIyM30.NRqoMzOIkZ9neazBCbgIwVkDSIGqCohsMgsIFF9ULp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);